<project xmlns="http://maven.apache.org/POM/4.0.0"echo          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"echo          xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">echo     <modelVersion>4.0.0</modelVersion>echo     <groupId>com.demo</groupId>echo     <artifactId>TomcatMavenDemo</artifactId>echo     <version>1.0-SNAPSHOT</version>echo     <packaging>war</packaging>echo     <build>echo         <finalName>TomcatMavenDemo</finalName>echo         <plugins>echo             <plugin>echo                 <groupId>org.apache.maven.plugins</groupId>echo                 <artifactId>maven-war-plugin</artifactId>echo                 <version>3.3.2</version>echo             </plugin>echo         </plugins>echo     </build>echo </project>
